export default {
    productsTable: {
        selected: [],
        search: '',
        headers: [
            {
                text: '商品ID',
                align: 'start',
                sortable: true,
                value: 'name',
            },
            { text: '事业部', value: 'company' },
            { text: '组别', value: 'city' },
            { text: '持品人', value: 'state' },
            { text: '店铺名', value: 'aaaaa' },
            { text: '产品名', value: 's' },
            { text: '一级类目', value: 'd' },
            { text: '品类扣点', value: 'f' },
            { text: '品类运费险', value: 'g' },
            { text: '每单运费', value: 'h' },
            { text: '子/主订单附带比', value: 'j' },
            { text: '运费/总货款', value: 'k' },
            { text: '发货方式', value: 'l' },
            { text: '聚水潭仓库', value: 'q' },
            { text: '厂家名', value: 'w' },
            { text: '厂家群名', value: 'e' },
            { text: '厂家收款账户', value: 'r' },
            { text: '厂家账户号码', value: 't' },
            { text: '厂家退货-收件人', value: 'y' },
            { text: '厂家退货-收件手机号', value: 'u' },
            { text: '厂家退货-收件地址', value: 'i' },
        ],
        products: [
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '696548761868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '纪梵希',
                's': '手提包',
                'd': '箱包皮具/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '334455461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '李宁',
                's': '书包',
                'd': '箱包皮具/热销女包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false

            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false

            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
            {
                name: '674786461868',
                company: '某某部',
                city: '某某组',
                state: '王毅',
                aaaaa: '辰琦',
                's': '拉杆箱',
                'd': '箱包皮具/热销女包/男包',
                'f': '0.11',
                'g': '0.15',
                'h': '0',
                'j': 'null',
                'k': 'null',
                'l': '聚水潭/手动/其它',
                'q': 'null',
                'w': 'A',
                'e': 'null',
                'r': '支付宝/某某银行',
                't': 'null',
                'y': 'null',
                'u': 'null',
                'i': 'null',
                select: false
            },
        ],
    },
}
